<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrDsgvo\GUI;

use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use ilSrDsgvoPlugin;
use srag\DIC\SrDsgvo\DICTrait;

/**
 * Class GUI
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @package           srag\Plugins\SrDsgvo\GUI
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy srag\Plugins\SrDsgvo\GUI\GUI: ilUIPluginRouterGUI
 */
class GUI {

	use DICTrait;
	use SrDsgvoTrait;
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
	const CMD_SOME = "some";


	/**
	 * GUI constructor
	 */
	public function __construct() {

	}


	/**
	 *
	 */
	public function executeCommand()/*: void*/ {
		$next_class = self::dic()->ctrl()->getNextClass($this);

		switch (strtolower($next_class)) {
			default:
				$cmd = self::dic()->ctrl()->getCmd();

				switch ($cmd) {
					case self::CMD_SOME:
						$this->{$cmd}();
						break;
					default:
						break;
				}
				break;
		}
	}


	/**
	 *
	 */
	protected function some()/*: void*/ {
		self::output()->output("some", true);
	}
}
