<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use srag\RemovePluginDataConfirm\SrDsgvo\AbstractRemovePluginDataConfirm;

/**
 * Class SrDsgvoRemoveDataConfirm
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy SrDsgvoRemoveDataConfirm: ilUIPluginRouterGUI
 */
class SrDsgvoRemoveDataConfirm extends AbstractRemovePluginDataConfirm {

	use SrDsgvoTrait;
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
}
