<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use srag\DIC\SrDsgvo\DICTrait;
use srag\Plugins\SrDsgvo\Config\Config;

/**
 * Class ilSrDsgvoUIHookGUI
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilSrDsgvoUIHookGUI extends ilUIHookPluginGUI {

	use DICTrait;
	use SrDsgvoTrait;
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
	const PLUGIN_INIT = "plugin_init";
	/**
	 * @var bool[]
	 */
	protected static $load = [
		self::PLUGIN_INIT => false
	];


	/**
	 * ilSrDsgvoUIHookGUI constructor
	 */
	public function __construct() {

	}


	/**
	 * @param string $a_comp
	 * @param string $a_part
	 * @param array  $a_par
	 *
	 * @return array
	 */
	public function getHTML(/*string*/ $a_comp, /*string*/ $a_part, /*array*/ $a_par = []): array {

		if (!self::$load[self::PLUGIN_INIT]) {

			if ($a_part == "template_get" && Config::getField(Config::HINT_EMBEDED_VIDEO_ACTIVE)) {
				self::dic()->ui()->mainTemplate()
					->addCss("./Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/SrDsgvo/vendor/a-v-l/dsgvo-video-embed/css/dsgvo-video-embed.css");
				self::dic()->ui()->mainTemplate()
					->addJavaScript("Customizing/global/plugins/Services/UIComponent/UserInterfaceHook/SrDsgvo/vendor/a-v-l/dsgvo-video-embed/js/dsgvo-video-embed.js");
				self::$load[self::PLUGIN_INIT] = true;
			}
		}

		return [ "mode" => self::KEEP, "html" => "" ];
	}
}
