<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../vendor/autoload.php";

use srag\Plugins\SrDsgvo\Config\ConfigFormGUI;
use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use srag\ActiveRecordConfig\SrDsgvo\ActiveRecordConfigGUI;

/**
 * Class ilSrDsgvoConfigGUI
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ilSrDsgvoConfigGUI extends ActiveRecordConfigGUI {

	use SrDsgvoTrait;
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
	/**
	 * @var array
	 */
	protected static $tabs = [ self::TAB_CONFIGURATION => ConfigFormGUI::class ];
}
