<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrDsgvo\Config;

use ilCheckboxInputGUI;
use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use ilSrDsgvoPlugin;
use ilTextInputGUI;
use srag\ActiveRecordConfig\SrDsgvo\ActiveRecordConfigFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @package srag\Plugins\SrDsgvo\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ConfigFormGUI extends ActiveRecordConfigFormGUI {

	use SrDsgvoTrait;
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
	const CONFIG_CLASS_NAME = Config::class;


	/**
	 * @inheritdoc
	 */
	protected function initFields()/*: void*/ {
		$this->fields = [
			Config::HINT_EMBEDED_VIDEO_ACTIVE => [
				self::PROPERTY_CLASS => ilCheckboxInputGUI::class,
			]
		];
	}
}
