<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrDsgvo\Config;

use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use ilSrDsgvoPlugin;
use srag\ActiveRecordConfig\SrDsgvo\ActiveRecordConfig;

/**
 * Class Config
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @package srag\Plugins\SrDsgvo\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class Config extends ActiveRecordConfig {

	use SrDsgvoTrait;
	const TABLE_NAME = "ui_uihk_srds_config";
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
	const HINT_EMBEDED_VIDEO_ACTIVE = "hint_embeded_videos";
	/**
	 * @var array
	 */
	protected static $fields = [
		self::HINT_EMBEDED_VIDEO_ACTIVE => self::TYPE_BOOLEAN
	];
}
