<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrDsgvo\Access;

use srag\Plugins\SrDsgvo\Utils\SrDsgvoTrait;
use ilSrDsgvoPlugin;
use srag\DIC\SrDsgvo\DICTrait;

/**
 * Class Access
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @package srag\Plugins\SrDsgvo\Access
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Access {

	use DICTrait;
	use SrDsgvoTrait;
	const PLUGIN_CLASS_NAME = ilSrDsgvoPlugin::class;
	/**
	 * @var self
	 */
	protected static $instance = null;


	/**
	 * @return self
	 */
	public static function getInstance(): self {
		if (self::$instance === null) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * Access constructor
	 */
	private function __construct() {

	}
}
