<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrDsgvo\Utils;

use srag\Plugins\SrDsgvo\Access\Access;
use srag\Plugins\SrDsgvo\Access\Ilias;

/**
 * Trait SrDsgvoTrait
 *
 * Generated by srag\PluginGenerator v0.13.1
 *
 * @package srag\Plugins\SrDsgvo\Utils
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
trait SrDsgvoTrait {

	/**
	 * @return Access
	 */
	protected static function access(): Access {
		return Access::getInstance();
	}


	/**
	 * @return Ilias
	 */
	protected static function ilias(): Ilias {
		return Ilias::getInstance();
	}
}
